import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'chevy' at '9/27/16 1:21 PM' with Gradle 2.14.1
 *
 * @author chevy, @date 9/27/16 1:21 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Triangle_Sum classUnderTest = new Triangle_Sum();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
