/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'chevy' at '9/27/16 1:21 PM' with Gradle 2.14.1
 *
 * @author chevy, @date 9/27/16 1:21 PM
 */
public class Triangle_Sum {
    public boolean someLibraryMethod() {
        return true;
    }
}
