/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Hang' at '9/27/16 2:07 PM' with Gradle 3.1
 *
 * @author Hang, @date 9/27/16 2:07 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
